### ISSUE TITLE
colourize the prompt

### ISSUE THREAD

**Issue by alesparza** [CIS548/docker-env#19]
There were some requests last semester to make the docker prompt have colour (similar to how vagrant looked).  What is the possibility of modifying the bash profile to include colors for username and current directory?

Here is a basic resource: [change bash colours](https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/)

**Comment by kuang-da** [comment]
Based on this [SO](https://stackoverflow.com/questions/33493456/docker-bash-prompt-does-not-display-color-output), I tried to set the environmental variable as follows, but it seems not ideal...

https://github.com/CIS548/docker-env/blob/327124d3ea6be693498bf4db4b9ad3e2a342465f/docker-compose.yml#L7

**Comment by kuang-da** [comment]
Maybe we could try this?

https://stackoverflow.com/a/41202403/9936569

**Comment by kuang-da** [comment]
The main difficulty is that we should have a `.bashrc` file in the container's home directory. But currently, docker binds the working directory in the host os into the home directory. So the `.bashrc` file will be wiped out.

The easiest solution is to change students' working directory from home to `~/cit595`.

Then we can easily use `ohmyzsh` to make the docker looks more colorful. 

But the demo video will be affected since the environment is not the same.

**Comment by alesparza** [comment]
Yikes, hate to have to redo those.  I guess it's not super necessary then
